pipeline:
  name: "ecommerce_realistic_transactions_pipeline"
  version: "1.0.0"
  description: "Realistic e-commerce transactions ETL pipeline with comprehensive data validation"

extract:
  source_type: "csv"
  source_path: "data/input/ecommerce_transactions_realistic.csv"
  batch_size: 10000
  encoding: "utf-8"
  delimiter: ","

transform:
  enable_cleaning: true
  enable_validation: true
  enable_feature_engineering: true
  
  cleaning_rules:
    remove_duplicates: true
    handle_missing_values: "drop"
    fill_value: "Unknown"
    remove_outliers: true
    outlier_threshold: 3.0
    
  validation_rules:
    required_columns: ["transaction_id", "amount", "currency", "transaction_date", "status"]
    data_types:
      transaction_id: "object"
      amount: "float64"
      currency: "object"
      transaction_date: "datetime64[ns]"
      status: "object"
      quantity: "int64"
      unit_price: "float64"
    constraints:
      amount: ">= -1000 and <= 10000"  # Allow refunds but cap at reasonable limits
      quantity: ">= 0 and <= 100"
      unit_price: ">= 0 and <= 5000"
      status: "in ['completed', 'pending', 'failed', 'cancelled', 'refund', 'processing']"
      currency: "in ['USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY']"
      
  feature_engineering:
    create_date_features: true
    create_numeric_features: true
    text_processing: true
    
load:
  output_format: "parquet"
  output_path: "data/output/ecommerce_realistic/"
  compression: "snappy"
  
  parquet_options:
    index: false
    compression: "snappy"
    
logging:
  level: "${LOG_LEVEL}"
  file_path: "logs/ecommerce_realistic_pipeline.log"
  max_file_size: "10MB"
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  console_enabled: true
  console_level: "INFO"

monitoring:
  enable_metrics: true
  enable_progress_bar: true
  enable_execution_time: true
  track_record_count: true
  track_processing_time: true
  track_error_count: true

error_handling:
  max_retries: "${MAX_RETRIES}"
  retry_delay: 5
  continue_on_error: false
  log_errors: true

development:
  enable_hot_reload: true
  enable_debug_mode: false
  enable_profiling: false
